services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: all
    environment:
      # execution config
      - ENV=prod
      - USE_CUDA_DOCKER=True
      - CORS_ALLOW_ORIGIN=http://localhost
      # general application settings
      - ENABLE_EVALUATION_ARENA_MODELS=False
      # AI API settings
      - ENABLE_OPENAI_API=False
      - OLLAMA_BASE_URL=http://ollama:11434
      # web search settings
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=duckduckgo # api keys set in secrets.env
    env_file:
      # secrets
      - secrets.env
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: all

volumes:
  open-webui: {}
  ollama: {}
